[semantic_release]
allow_zero_version = true
commit_author = "github-actions <actions@github.com>"
commit_message = "chore(release): {version} [skip ci]"
tag_format = "v{version}"
version_variables = ["VERSION:*"]

[semantic_release.branches.develop]
match = "develop"
prerelease = false
prerelease_token = "dev"

[semantic_release.remote]
type = "github"
token = { env = "GH_TOKEN" }


